---
install:
- yes | sudo apt-add-repository ppa:texlive-backports/ppa
- sudo apt-get update -qq
- sudo apt-get install latex-xcolor texlive-latex-extra texlive-fonts-recommended
  texlive-fonts-extra biblatex biber
script:
- make ctan